### ISSUE TITLE
Error during installation 

### ISSUE THREAD

**Issue by manojsitapara** [telebotter/django-telegrambot#15]
I did try to install by following command

`pip install -e git+https://github.com/telebotter/django-telegrambot.git#egg=django-telegrambot --upgrade`

>  FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'

Is anybody else also facing same error?

**Comment by maxatp** [comment]
This is happening because of the last changes from Jul 20, 2020. You can install the previous commit:
```
pip install -e git+https://github.com/telebotter/django-telegrambot.git@5f07ec585086eca9f26d10305eca58fe21c67a6d#egg=django-telegrambot --upgrade
```

**Comment by lukruh** [comment]
sorry that was my bad I change the readme to markdown, forgot to edit the package info..

**Comment by lukruh** [comment]
I fixed the readme in the latest commit, the installation should work again. If you have installed the previous commit as maxatp suggested you are fine too, the actual code has not changed..

**Comment by manojsitapara** [comment]
Thanks !! It is working fine.
