### ISSUE TITLE
Old Handler API is deprecated - see https://git.io/fxJuV for details

### ISSUE THREAD

**Issue by purwowd** [telebotter/django-telegrambot#16]
![image](https://user-images.githubusercontent.com/17087219/91885837-9d8fc400-ecb2-11ea-90f2-d15a827bded2.png)

**Comment by lukruh** [comment]
I think the Deprecation Warning is not related to the Unauthorized Error.

**Comment by purwowd** [comment]
I see, can you update sampleproject to django latest version?

Thanks.

**Comment by lukruh** [comment]
It's on my todo list but I don't have time for that in the moment. Feel free to fix the example and create a PR

**Comment by purwowd** [comment]
url(r'^', include('django_telegrambot.urls')),
url(r'^$', include('bot.urls')),

What different r'^' and r'^$' ?
r'^$' = path('', include('django_telegrambot.urls'))
r'^' = ???
